remote_theme: mmistakes/minimal-mistakes

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
